const menuItems = [

//veg item Main course
{name:"Veg Biryani", full_price: 120 , category: "Main Course", type: "Veg", image: "./images/Veg Biriyani.png" },
{name:"Paneer Butter Masala", full_price:200,half_price:100, category: "Main Course", type: "Veg", image: "./images/paneer-butter-masala.png" },
{name:"Daal Tadka", full_price: 100 ,half_price:50, category: "Main Course", type: "Veg", image: "./images/Dal Tadka.png" },
{name:"Sahi Paneer", full_price: 220, category: "Main Course", type: "Veg", image: "./images/shahi-paneer.png" },
{name:"Veg Pulao", full_price: 120 , category: "Main Course", type: "Veg", image: "./images/Veg Pulao.png" },
{name:"Kadhai Paneer", full_price: 200,half_price:100 , category: "Main Course", type: "Veg", image: "./images/kadhai-paneer.png" },
{name:"Matar Paneer", full_price: 220,half_price:110 , category: "Main Course", type: "Veg", image: "" },
{name:"Paneer Do Piaza", full_price: 220 , category: "Main Course", type: "Veg", image: "" },
{name:"Paneer Bhujia", full_price: 150 , category: "Main Course", type: "Veg", image: "" },
{name:"Handi Paneer", full_price: 220 ,half_price:110, category: "Main Course", type: "Veg", image: "" },
{name:"Mix Veg", full_price: 120 ,half_price:60, category: "Main Course", type: "Veg", image: "" },
{name:"Mushroom Matar", full_price: 220 , category: "Main Course", type: "Veg", image: "" },

    //non-veg item Main course
    { name: "Butter Chicken", full_price: 240,half_price:120 , category: "Main Course", type: "Non-Veg", image: "./images/butter-chicken.png" },
{name:"Kadhai Chicken", full_price: 240,half_price:120 , category: "Main Course", type: "Non-Veg", image: "" },
{name:"Handi Chicken", full_price: 240,half_price:120 , category: "Main Course", type: "Non-Veg", image: "" },
{name:"Chicken Biryani", full_price: 160 , category: "Main Course", type: "Non-Veg", image: "" },
{name:"Chicken Do Piaza", full_price: 260, category: "Main Course", type: "Non-Veg", image: "" },
//breakfast item
{name:"Samosa",full_price: 10 , category: "Breakfast", type: "Veg", image: "./images/samosa.png"  },
{name:"Kachori",full_price: 10 , category: "Breakfast", type: "Veg", image: ""},
{name:"Vada",full_price: 60 , category: "Breakfast", type: "Veg", image: ""},
{name:"Idli",full_price: 60 , category: "Breakfast", type: "Veg", image: "./images/idli.png" },
{name:"Aloo Bonda",full_price: 10 , category: "Breakfast", type: "Veg", image: ""},
{name:"Bread Pakoda",full_price: 15 , category: "Breakfast", type: "Veg", image: ""},
{name:"Omelette 2 Egg",full_price: 35 , category: "Breakfast", type: "Non-Veg", image: ""},
{name:"Bread Omelette",full_price: 50 , category: "Breakfast", type: "Non-Veg", image: ""},
{name:"Masala Dosa",full_price:70 , category: "Breakfast", type: "Veg", image: ""},
{name: "Plain Dosa",full_price: 60 , category: "Breakfast", type: "Veg", image: ""},
{name:"Onion Plain Dosa",full_price: 70 , category: "Breakfast", type: "Veg", image: ""},
{name:"Onion Masala Dosa",full_price: 80 , category: "Breakfast", type: "Veg", image: ""},
{name:"Onion Uttapam",full_price: 70 , category: "Breakfast", type: "Veg", image: ""},
{name:"Egg Masala Dosa",full_price: 90 , category: "Breakfast", type: "Non-Veg", image: ""},
{name:"Egg Plain Dosa",full_price: 85 , category: "Breakfast", type: "Non-Veg", image: ""},
{name:"Aloo Paratha",full_price: 50 , category: "Breakfast", type: "Veg", image: ""},
{name:"Onion Paratha",full_price: 50 , category: "Breakfast", type: "Veg", image: ""},
{name:"Paneer Paratha",full_price: 80 , category: "Breakfast", type: "Veg", image: ""},
{name:"Plain Paratha",full_price: 40 , category: "Breakfast", type: "Veg", image: ""},
{name:"Chole Bhature",full_price: 70 , category: "Breakfast", type: "Veg", image: ""},
{name:"Dhokla",full_price: 15 , category: "Breakfast", type: "Veg", image: ""},
{name:"Dahi Vada",full_price: 30 , category: "Breakfast", type: "Veg", image: ""},
{name:"Dahi Kachori",full_price: 30 , category: "Breakfast", type: "Veg", image: ""},

//Starter veg
{name:"Veg Noodle",full_price: 60 , category: "Starter", type: "Veg", image: ""},
{name:"Veg Maggi",full_price: 30 , category: "Starter", type: "Veg", image: ""},
{name:"Veg Burger",full_price: 60 , category: "Starter", type: "Veg", image: ""},
{name:"Veg Roll",full_price: 50 , category: "Starter", type: "Veg", image: ""},
{name:"Chilli Paneer",full_price: 160 , category: "Starter", type: "Veg", image: ""},
{name:"Paneer Manchurian",full_price: 140 , category: "Starter", type: "Veg", image: ""},
{name:"Gobhi Manchurian",full_price: 140 , category: "Starter", type: "Veg", image: ""},
{name:"Paneer Manchurian Gravy",full_price: 160 , category: "Starter", type: "Veg", image: ""},
{name:"Gobhi Manchurian Gravy",full_price: 160 , category: "Starter", type: "Veg", image: ""},
{name:"Veg Mommo",full_price: 50 , category: "Starter", type: "Veg", image: ""},
{name:"Paneer Tikka",full_price: 80 , category: "Starter", type: "Veg", image: ""},
//starter non-veg
{name:"Chicken Noodle",full_price: 100 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chicken Burger",full_price: 100 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chicken Manchurian",full_price: 160 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chilli Chicken",full_price: 160 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chicken Manchurian Gravy",full_price: 180 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chilli Chicken Gravy",full_price: 180 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chicken Roll",full_price: 100 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Egg Roll",full_price: 80 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Chicken Tikka",full_price: 100 , category: "Starter", type: "Non-Veg", image: ""},
{name:"Tandoori Leg Piece",full_price: 70 , category: "Starter", type: "Non-Veg", image: ""},

//Roti & Rice
{name:"Steam Rice", full_price: 60 , category: "Rice", type: "Veg", image: "./images/steamed rice.png" },
{name:"Jeera Rice", full_price: 70 , category: "Rice", type: "Veg", image: "./images/Jeera Rice.png" },
{name:"Veg Fried Rice", full_price: 80 , category: "Rice", type: "Veg", image: "" },
{name:"Veg Fried Rice", full_price: 80 , category: "Rice", type: "Veg", image: "" },
{name:"Paneer Fried Rice", full_price: 100 , category: "Rice", type: "Veg", image: "" },
{name :"Sezwan Fried Rice", full_price: 100 , category: "Rice", type: "Veg", image: "" },
{name:"Chcicken Fried Rice", full_price: 120 , category: "Rice", type: "Non-Veg", image: "" },
{name:"Egg Fried Rice", full_price: 100 , category: "Rice", type: "Non-Veg", image: "" },

{name:"Plain Tawa Roti", full_price: 9 , category: "Roti", type: "Veg", image: "" },
{name:"Butter Tawa Roti", full_price: 10 , category: "Roti", type: "Veg", image: "" },
{name:"Triangle Paratha", full_price: 15 , category: "Roti", type: "Veg", image: "" },


    
];